### ISSUE TITLE
workbench can be dug with material inside

### ISSUE THREAD

**Issue by Bastrabun** [minetest-mods/crafting_bench#8]
Players can dig their workbench with material left inside, causing the material to be lost when dug.

Please make it that the workbench cannot be dug when items are anywhere inside.

For my reference 1658

**Comment by tenplus1** [comment]
https://github.com/minetest-mods/crafting_bench/pull/11

**Comment by corarona** [comment]
From what I can tell this was fixed by #11

**Comment by Niklp09** [comment]
Fixed in https://github.com/minetest-mods/crafting_bench/commit/3b3309ea43fee8a171c4c5bfa7ffaf38ee421144.
